/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Seminarska.java
 *
 * Created on Mar 12, 2013, 10:45:23 PM
 */
package Seminarska;

import com.mysql.jdbc.Connection;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JFileChooser;

/**
 *
 * @author asus
 */
public class Seminarska extends javax.swing.JFrame {

    String pass;
    /** Creates new form DomacaNaloga1 */
    public Seminarska() {
        initComponents();
    }

    public Seminarska(String name){
        initComponents();
        pass = name;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        Iskustvo = new javax.swing.ButtonGroup();
        broj_sjedista = new javax.swing.ButtonGroup();
        osiguranje = new javax.swing.ButtonGroup();
        Kasko = new javax.swing.ButtonGroup();
        Tabs = new javax.swing.JTabbedPane();
        Pocetak = new javax.swing.JPanel();
        Napred1 = new javax.swing.JButton();
        Spremi2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textContent = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Marka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Boja = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Obujam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TipVozila = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        br_sjedista1 = new javax.swing.JRadioButton();
        br_sjedista2 = new javax.swing.JRadioButton();
        br_sjedista3 = new javax.swing.JRadioButton();
        br_sjedista4 = new javax.swing.JRadioButton();
        br_sjedista5 = new javax.swing.JRadioButton();
        br_sjedistaOstalo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        br_sjedista = new javax.swing.JTextField();
        Moc = new javax.swing.JTextField();
        Benzin = new javax.swing.JRadioButton();
        Dizel = new javax.swing.JRadioButton();
        Plin = new javax.swing.JRadioButton();
        Natrag1 = new javax.swing.JButton();
        Napred2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Ime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Prezime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Ulica = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dat_rodjenja = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Grad = new javax.swing.JTextField();
        Postanski = new javax.swing.JLabel();
        Posta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Kucni = new javax.swing.JTextField();
        Natrag2 = new javax.swing.JButton();
        Napred3 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Ao = new javax.swing.JRadioButton();
        Aoplus = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        Puno = new javax.swing.JRadioButton();
        Odbitna_fransiza = new javax.swing.JRadioButton();
        Bez = new javax.swing.JRadioButton();
        dodOsiguranje = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        Natrag3 = new javax.swing.JButton();
        Napred4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Mlad = new javax.swing.JRadioButton();
        Iskusan = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        Mjeseci = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dan_registracije = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        godReg = new javax.swing.JTextField();
        reg_oznaka = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Natrag4 = new javax.swing.JButton();
        Napred5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        gSpremi = new javax.swing.JButton();
        gPobrisiSve = new javax.swing.JButton();
        Natrag5 = new javax.swing.JButton();
        gKraj = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        fileInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datoteka = new javax.swing.JMenu();
        gumbOpen = new javax.swing.JMenuItem();
        gumbSpremi = new javax.swing.JMenuItem();
        gumbClear = new javax.swing.JMenuItem();
        gumbQuit = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TechCar");

        Napred1.setText("Napred");
        Napred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        Spremi2.setText("Spremi");
        Spremi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHandler(evt);
            }
        });

        jScrollPane1.setViewportView(textContent);

        javax.swing.GroupLayout PocetakLayout = new javax.swing.GroupLayout(Pocetak);
        Pocetak.setLayout(PocetakLayout);
        PocetakLayout.setHorizontalGroup(
            PocetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PocetakLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Spremi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(Napred1)
                .addGap(133, 133, 133))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PocetakLayout.setVerticalGroup(
            PocetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PocetakLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PocetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Napred1)
                    .addComponent(Spremi2)))
        );

        Tabs.addTab("Početak", Pocetak);

        jLabel1.setText("Podatci o vozilu");

        jLabel2.setText("*Marka");

        jLabel3.setText("*Model");

        jLabel4.setText("Boja");

        jLabel6.setText("Moć (kW)");

        jLabel5.setText("Radni obujam (cm3)");

        jLabel7.setText("*Gorivo");

        jLabel8.setText("*Tip vozila");

        TipVozila.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Osobni auto", "Autobus", "Kamion", "Traktor", "Motor" }));

        jLabel9.setText("*Broj sjedišta");

        broj_sjedista.add(br_sjedista1);
        br_sjedista1.setSelected(true);
        br_sjedista1.setText("1");

        broj_sjedista.add(br_sjedista2);
        br_sjedista2.setText("2");

        broj_sjedista.add(br_sjedista3);
        br_sjedista3.setText("3");

        broj_sjedista.add(br_sjedista4);
        br_sjedista4.setText("4");

        broj_sjedista.add(br_sjedista5);
        br_sjedista5.setText("5");

        broj_sjedista.add(br_sjedistaOstalo);
        br_sjedistaOstalo.setText("Ostalo");

        jLabel10.setText("Ako ostalo, upiši");

        Benzin.setText("Benzin");

        Dizel.setText("Dizel");

        Plin.setText("Plin");

        Natrag1.setText("Natrag");
        Natrag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        Napred2.setText("Napred");
        Napred2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        jLabel16.setText("* - obavezna polja");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Boja, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(Model, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Marka, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Moc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                        .addComponent(Benzin)
                                                        .addGap(35, 35, 35)
                                                        .addComponent(Dizel)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(Plin))))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(TipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(br_sjedista1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(br_sjedista2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(br_sjedista3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(br_sjedista4)
                                        .addGap(18, 18, 18)
                                        .addComponent(br_sjedista5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(br_sjedistaOstalo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Obujam, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(br_sjedista, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Natrag1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Napred2)
                        .addGap(158, 158, 158))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(Moc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Boja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(TipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(br_sjedista1)
                            .addComponent(br_sjedista2)
                            .addComponent(br_sjedista3)
                            .addComponent(br_sjedista4)
                            .addComponent(br_sjedista5)
                            .addComponent(br_sjedistaOstalo)
                            .addComponent(jLabel5)
                            .addComponent(Obujam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(Benzin)
                        .addComponent(Dizel)
                        .addComponent(Plin)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(br_sjedista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Natrag1)
                    .addComponent(Napred2))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Tabs.addTab("Vozilo", jPanel2);

        jLabel11.setText("Podatci o osiguraniku");

        jLabel12.setText("*Ime");

        jLabel13.setText("*Prezime");

        jLabel15.setText("*Ulica");

        jLabel18.setText("*Datum rođenja");

        dat_rodjenja.setText("dd.mm.gggg");
        dat_rodjenja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dat_rodjenjaskrijPomoc(evt);
            }
        });
        dat_rodjenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dat_rodjenjaActionPerformed(evt);
            }
        });

        jLabel14.setText("*Grad");

        Postanski.setText("*Poštanski broj");

        jLabel17.setText("*Kućni broj");

        Natrag2.setText("Natrag");
        Natrag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        Napred3.setText("Napred");
        Napred3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        jLabel40.setText("*ID");

        jLabel28.setText("* - obavezna polja");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(Natrag2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Ime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ulica, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Postanski, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Posta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Prezime, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                                .addComponent(Kucni, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(Grad, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(dat_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Napred3)
                                .addGap(91, 91, 91))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel28)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Ime)
                    .addComponent(Prezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Ulica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Kucni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Postanski)
                    .addComponent(Posta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dat_rodjenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel14)
                    .addComponent(Grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Natrag2)
                    .addComponent(Napred3))
                .addGap(21, 21, 21))
        );

        Tabs.addTab("Osiguranik 1", jPanel4);

        jLabel20.setText("Podatci o osiguraniku");

        jLabel21.setText("Osnovno osiguranje");

        osiguranje.add(Ao);
        Ao.setText("AO");

        osiguranje.add(Aoplus);
        Aoplus.setText("AO+");

        jLabel22.setText("Kasko");

        Kasko.add(Puno);
        Puno.setText("Puno");

        Kasko.add(Odbitna_fransiza);
        Odbitna_fransiza.setText("Odb.franšiza");

        Kasko.add(Bez);
        Bez.setText("Bez");

        dodOsiguranje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Оsiguranje od prometne nesreće", "Osiguranje stakala", "Osiguranje putnika", "Osiguranje treće osobe", "Osiguranje guma", "Osiguranje protiv snjega", "Osiguranje protiv tuče" }));

        jLabel23.setText("Dod. osiguranje");

        Natrag3.setText("Natrag");
        Natrag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        Napred4.setText("Napred");
        Napred4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        jLabel19.setText("Iskustvo");

        Iskustvo.add(Mlad);
        Mlad.setText("Mlad vozač");

        Iskustvo.add(Iskusan);
        Iskusan.setText("Iskusan vozač");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Natrag3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Napred4)
                .addGap(39, 39, 39))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(Ao)
                                .addGap(81, 81, 81)
                                .addComponent(Aoplus))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(Mlad)
                                        .addGap(70, 70, 70)
                                        .addComponent(Iskusan))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(dodOsiguranje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(Puno)
                                        .addGap(33, 33, 33)
                                        .addComponent(Odbitna_fransiza)
                                        .addGap(44, 44, 44)
                                        .addComponent(Bez)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ao)
                    .addComponent(Aoplus))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Puno)
                    .addComponent(Odbitna_fransiza)
                    .addComponent(Bez))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodOsiguranje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mlad)
                        .addComponent(Iskusan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Natrag3)
                    .addComponent(Napred4))
                .addGap(26, 26, 26))
        );

        Tabs.addTab("Osiguranik 2", jPanel5);

        Mjeseci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Siječanj", "Veljača", "Ožujak", "Travanj", "Svibanj", "Lipanj", "Srpanj", "Kolovoz", "Rujan", "Listopad", "Studeni", "Prosinac" }));

        jLabel25.setText("Mjesec prve registracije");

        jLabel24.setText("Podatci o registraciji");

        jLabel26.setText("Dan prve registracije");

        dan_registracije.setText("dd");
        dan_registracije.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dan_registracijeskrijPomoc(evt);
            }
        });
        dan_registracije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dan_registracijeActionPerformed(evt);
            }
        });

        jLabel27.setText("Godina prve registracije");

        godReg.setText("gggg");
        godReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dan_registracijeskrijPomoc(evt);
            }
        });
        godReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godRegActionPerformed(evt);
            }
        });

        jLabel29.setText("Registarska oznaka");

        Natrag4.setText("Natrag");
        Natrag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        Napred5.setText("Napred");
        Napred5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(Natrag4)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dan_registracije, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(godReg))
                                    .addComponent(reg_oznaka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mjeseci, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 566, Short.MAX_VALUE)
                                .addComponent(Napred5)
                                .addGap(54, 54, 54))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(dan_registracije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Mjeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(godReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_oznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Natrag4)
                    .addComponent(Napred5))
                .addGap(34, 34, 34))
        );

        Tabs.addTab("Registracija", jPanel6);

        gSpremi.setText("Spremi");
        gSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSpremimethod(evt);
            }
        });

        gPobrisiSve.setText("Pobriši sve");
        gPobrisiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPobrisiSvemethod(evt);
            }
        });

        Natrag5.setText("Natrag");
        Natrag5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbi(evt);
            }
        });

        gKraj.setText("Odjava");
        gKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gKrajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Natrag5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gKraj)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(gPobrisiSve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(gSpremi)
                .addGap(206, 206, 206))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gPobrisiSve)
                    .addComponent(gSpremi))
                .addGap(84, 84, 84)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gKraj)
                    .addComponent(Natrag5))
                .addGap(30, 30, 30))
        );

        Tabs.addTab("Kraj", jPanel7);

        fileInfo.setText("Status:");

        Datoteka.setMnemonic('D');
        Datoteka.setText("Datoteka");

        gumbOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        gumbOpen.setMnemonic('O');
        gumbOpen.setText("Otvori");
        gumbOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openClearQuitHandler(evt);
            }
        });
        Datoteka.add(gumbOpen);

        gumbSpremi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        gumbSpremi.setMnemonic('S');
        gumbSpremi.setText("Spremi");
        gumbSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSpremimethod(evt);
            }
        });
        Datoteka.add(gumbSpremi);

        gumbClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        gumbClear.setMnemonic('P');
        gumbClear.setText("Pobrisi");
        gumbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPobrisiSvemethod(evt);
            }
        });
        Datoteka.add(gumbClear);

        gumbQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        gumbQuit.setMnemonic('I');
        gumbQuit.setText("Izlaz");
        gumbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openClearQuitHandler(evt);
            }
        });
        Datoteka.add(gumbQuit);

        jMenuBar1.add(Datoteka);

        Pomoc.setMnemonic('P');
        Pomoc.setText("Pomoc");

        jMenuItem1.setMnemonic('A');
        jMenuItem1.setText("Author");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorHandler(evt);
            }
        });
        Pomoc.add(jMenuItem1);

        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileInfo))
        );

        Tabs.getAccessibleContext().setAccessibleName("Osiguranik");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void openClearQuitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openClearQuitHandler
    JFileChooser jfc = new JFileChooser();
    if (evt.getSource() == gumbQuit || evt.getSource() == gKraj){
        jOptionPane1.showMessageDialog(rootPane, "Odjava uspješna");
        System.exit(0);                
    } else if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION || evt.getSource() == gumbOpen){
        File f = jfc.getSelectedFile();
        try {
            textContent.read(new FileReader(f), null);
            fileInfo.setText("Otvorena datoteka: " + f.getName());
        } catch (Exception e){
            fileInfo.setText("Greška u čitanju.");
            System.err.print(e);
        }
        
        String connectionURL= "jdbc:derby://localhost:1527/TechCar"; 
        try { 
            java.sql.Connection conn = DriverManager.getConnection(connectionURL, "darko", "darko"); 
            String sql = "SELECT * FROM UNTITLED"; 
            Statement st = conn.createStatement();                                   
            ResultSet rs=null; 
            rs=st.executeQuery(sql); 
            while(rs.next()){ 
                ID.setText(rs.getString("UserID"));
                Ime.setText(rs.getString("FirstName"));
                Prezime.setText(rs.getString("LastName"));
                Ulica.setText(rs.getString("Address"));
                Marka.setText(rs.getString("CarBrand"));
                Model.setText(rs.getString("CarModel"));
            } 
            rs.close(); 
            st.close(); 
            conn.close(); 
        } catch (SQLException ex) { 
            System.out.println("Connect failed!"); 
        }
    } 
}//GEN-LAST:event_openClearQuitHandler

    private void authorHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorHandler
       fileInfo.setText("Autоri: Darko Tarandek, Duje Šušak i Mislav Vukašina");
    }//GEN-LAST:event_authorHandler

    private void gSpremimethod(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSpremimethod
        if(evt.getSource() == gSpremi || evt.getSource() == gumbSpremi){
            spremi();
        }
    }//GEN-LAST:event_gSpremimethod

    private void gKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gKrajActionPerformed
        if (evt.getSource() == gKraj){
            jOptionPane1.showMessageDialog(rootPane, "Odjava uspješna");
            System.exit(0);
        }    
    }//GEN-LAST:event_gKrajActionPerformed

    private void gumbi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbi
        if(evt.getSource() == Napred1){
            Tabs.setSelectedIndex(1);
        }else if(evt.getSource() == Natrag1){
            Tabs.setSelectedIndex(0);
        }else if(evt.getSource() == Napred2){
            Tabs.setSelectedIndex(2);
        }else if(evt.getSource() == Natrag2){
            Tabs.setSelectedIndex(1);
        }else if(evt.getSource() == Napred3){
            Tabs.setSelectedIndex(3);
        }else if(evt.getSource() == Natrag3){
            Tabs.setSelectedIndex(2);
        }else if(evt.getSource() == Napred4){
            Tabs.setSelectedIndex(4);
        }else if(evt.getSource() == Natrag4){
            Tabs.setSelectedIndex(3);
        }else if(evt.getSource() == Napred5){
            Tabs.setSelectedIndex(5);
        }else if(evt.getSource() == Natrag5){
            Tabs.setSelectedIndex(4);
        }
    }//GEN-LAST:event_gumbi

    private void gPobrisiSvemethod(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPobrisiSvemethod
        if(evt.getSource() == gPobrisiSve || evt.getSource() == gumbClear){
            pobrisi();
        }
    }//GEN-LAST:event_gPobrisiSvemethod

    private void dan_registracijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dan_registracijeActionPerformed
        Calendar cld = Calendar.getInstance();
        cld.setLenient(false);
        cld.set(2013, 1, 39);
        System.out.println(cld.get(Calendar.YEAR)+" "+cld.get(Calendar.MONTH)+" "+cld.get(Calendar.DAY_OF_MONTH));
    }//GEN-LAST:event_dan_registracijeActionPerformed

    private void dan_registracijeskrijPomoc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dan_registracijeskrijPomoc
        if(evt.getSource() == dat_rodjenja){
            if(dat_rodjenja.getText().equalsIgnoreCase("dd.mm.gggg")){
                dat_rodjenja.setText("");
            }
        }else if(evt.getSource() == godReg){
            if(godReg.getText().equalsIgnoreCase("gggg")){
                godReg.setText("");
            }
        }else if(evt.getSource() == dan_registracije){
            if(dan_registracije.getText().equalsIgnoreCase("dd")){
                dan_registracije.setText("");
            }
        }    
    }//GEN-LAST:event_dan_registracijeskrijPomoc

    private void dat_rodjenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dat_rodjenjaActionPerformed
        Calendar cld = Calendar.getInstance();
        cld.setLenient(false);
        cld.set(2013, 1, 39);
        System.out.println(cld.get(Calendar.YEAR)+" "+cld.get(Calendar.MONTH)+" "+cld.get(Calendar.DAY_OF_MONTH));
    }//GEN-LAST:event_dat_rodjenjaActionPerformed

    private void dat_rodjenjaskrijPomoc(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dat_rodjenjaskrijPomoc
        if(evt.getSource() == dat_rodjenja){
            if(dat_rodjenja.getText().equalsIgnoreCase("dd.mm.gggg")){
                dat_rodjenja.setText("");
            }
        }else if(evt.getSource() == dan_registracije){
            if(dan_registracije.getText().equalsIgnoreCase("dd.")){
                dan_registracije.setText("");
            }
        }
    }//GEN-LAST:event_dat_rodjenjaskrijPomoc

    private void saveHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHandler
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION || evt.getSource() == Spremi2) {
        File f = jFileChooser1.getSelectedFile();
        fileInfo.setText(f.getName());
        try {
            textContent.write(new FileWriter(f));
            fileInfo.setText("Spremljena datoteka: " + f.getName());
        } catch (Exception e) {
            fileInfo.setText("Greška u čitanju.");
            System.err.print(e);
        }
    }
    }//GEN-LAST:event_saveHandler

    private void godRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_godRegActionPerformed

    private void pobrisi(){
        Boja.setText("");
        Kucni.setText("");
        Ime.setText("");
        Grad.setText("");
        Moc.setText("");
        Model.setText("");
        Posta.setText("");
        Prezime.setText("");
        Obujam.setText("");
        ID.setText("");
        dan_registracije.setText("dd");
        reg_oznaka.setText("");
        dat_rodjenja.setText("dd.mm.gggg");
        br_sjedista.setText("");
        Ulica.setText("");
        godReg.setText("gggg");
        Marka.setText("");
        TipVozila.setSelectedIndex(-1);
        Mjeseci.setSelectedIndex(-1);
        dodOsiguranje.setSelectedIndex(-1);
}
    
private void spremi(){
        
        if(jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION ){
            File f = jFileChooser1.getSelectedFile();
            try {
                PrintWriter out = new PrintWriter(new FileWriter(f));
                out.println("Podatci o osobi:");
                out.println();
                out.println("ID: " + ID.getText());
                out.println("Ime i prezime: " + Ime.getText() + " " + Prezime.getText());
                out.println("Datum rođenja: " + dat_rodjenja.getText());
                if(Mlad.isSelected()){
                    out.println("Iskustvo: Mlad vozač");    
                }else if(Iskusan.isSelected()){
                    out.println("Iskustvo: Iskusni vozač");
                }
                out.println("Adresa:");
                out.println(Ulica.getText() + " " + Kucni.getText());
                out.println(Posta.getText() + " " + Grad.getText());
                out.println("_____________________________________");
                out.println("Podatci o automobilu:");
                out.println();
                out.println("Marka: " + Marka.getText());
                out.println("Model: " + Model.getText());
                if(Benzin.isSelected()){
                    out.println("Gorivo: Benzin");
                }else if(Dizel.isSelected()){
                    out.println("Gorivo: Dizel");
                }else if(Plin.isSelected()){
                    out.println("Gorivo: Plin");
                }
                out.println("Moć: " + Moc.getText() + "kW");
                out.println("Radni obujam motora: " + Obujam.getText() + "cm3");
                if (br_sjedistaOstalo.isSelected()){
                    out.println("Broj sjedišta: " + br_sjedista.getText());
                }else if(br_sjedista1.isSelected()){
                    out.println("Broj sjedišta: 1");
                }else if(br_sjedista2.isSelected()){
                    out.println("Broj sjedišta: 2");
                }else if(br_sjedista3.isSelected()){
                    out.println("Broj sjedišta: 3");
                }else if(br_sjedista4.isSelected()){
                    out.println("Broj sjedišta: 4");
                }else if(br_sjedista5.isSelected()){
                    out.println("Broj sjedišta: 5");
                }
                out.println("Tip vozila: " + TipVozila.getSelectedItem().toString());
                out.println("Boja: " + Boja.getText());
                out.println("_____________________________________");                
                out.println("Podatci o registraciji:");
                out.println();
                out.println("Prva registracija: " + dan_registracije.getText() + " " + Mjeseci.getSelectedItem().toString() 
                                                  + " " + godReg.getText());
                out.println("Registarska oznaka: " + reg_oznaka.getText());            
                out.println("_____________________________________");               
                out.println("Podatci o osiguranju:");
                out.println();
                if(Ao.isSelected()){
                    out.println("Osnovno osiguranje: AO");                    
                }else if(Aoplus.isSelected()){
                    out.println("Osnovno osiguranje: AO+");
                }
                if(Bez.isSelected()){
                    out.println("Kasko zavarovanje: Bez");
                }else if(Odbitna_fransiza.isSelected()){
                    out.println("Kasko osiguranje: Odbitna franšiza");
                }else if(Puno.isSelected()){
                    out.println("Kasko osiguranje: Puno");
                }
                out.print("Dodatno osiguranje: " + dodOsiguranje.getSelectedItem().toString());
                out.close();
            } catch (Exception e) {
                System.err.print(e);
            }
        }
        
        String connectionURL = "jdbc:derby://localhost:1527/TechCar";
        String username = "darko";
        String password = "darko";
        
        try { 
            java.sql.Connection conn = DriverManager.getConnection(connectionURL, username, password); 
            String sql = "INSERT INTO DARKO.UNTITLED (USERID, FIRSTNAME, LASTNAME, ADDRESS, CARBRAND, CARMODEL, USERNAME, PASSWORD) VALUES ('"+ID.getText()+"', '"+Ime.getText()+"', '"+Prezime.getText()+"','"+Ulica.getText()+"', '"+Marka.getText()+"', '"+Model.getText()+"', 'darko', 'darko')"; 
            Statement st = conn.createStatement();                                   
            st.executeUpdate(sql);
            st.close();           
            conn.close();
        } catch (SQLException ex) { 
            System.out.println("Connect failed!"); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seminarska.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seminarska.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seminarska.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seminarska.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Seminarska().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ao;
    private javax.swing.JRadioButton Aoplus;
    private javax.swing.JRadioButton Benzin;
    private javax.swing.JRadioButton Bez;
    private javax.swing.JTextField Boja;
    private javax.swing.JMenu Datoteka;
    private javax.swing.JRadioButton Dizel;
    private javax.swing.JTextField Grad;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Ime;
    private javax.swing.JRadioButton Iskusan;
    private javax.swing.ButtonGroup Iskustvo;
    private javax.swing.ButtonGroup Kasko;
    private javax.swing.JTextField Kucni;
    private javax.swing.JTextField Marka;
    private javax.swing.JComboBox Mjeseci;
    private javax.swing.JRadioButton Mlad;
    private javax.swing.JTextField Moc;
    private javax.swing.JTextField Model;
    private javax.swing.JButton Napred1;
    private javax.swing.JButton Napred2;
    private javax.swing.JButton Napred3;
    private javax.swing.JButton Napred4;
    private javax.swing.JButton Napred5;
    private javax.swing.JButton Natrag1;
    private javax.swing.JButton Natrag2;
    private javax.swing.JButton Natrag3;
    private javax.swing.JButton Natrag4;
    private javax.swing.JButton Natrag5;
    private javax.swing.JTextField Obujam;
    private javax.swing.JRadioButton Odbitna_fransiza;
    private javax.swing.JRadioButton Plin;
    private javax.swing.JPanel Pocetak;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JTextField Posta;
    private javax.swing.JLabel Postanski;
    private javax.swing.JTextField Prezime;
    private javax.swing.JRadioButton Puno;
    private javax.swing.JButton Spremi2;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JComboBox TipVozila;
    private javax.swing.JTextField Ulica;
    private javax.swing.JTextField br_sjedista;
    private javax.swing.JRadioButton br_sjedista1;
    private javax.swing.JRadioButton br_sjedista2;
    private javax.swing.JRadioButton br_sjedista3;
    private javax.swing.JRadioButton br_sjedista4;
    private javax.swing.JRadioButton br_sjedista5;
    private javax.swing.JRadioButton br_sjedistaOstalo;
    private javax.swing.ButtonGroup broj_sjedista;
    private javax.swing.JTextField dan_registracije;
    private javax.swing.JTextField dat_rodjenja;
    private javax.swing.JComboBox dodOsiguranje;
    private javax.swing.JLabel fileInfo;
    private javax.swing.JButton gKraj;
    private javax.swing.JButton gPobrisiSve;
    private javax.swing.JButton gSpremi;
    private javax.swing.JTextField godReg;
    private javax.swing.JMenuItem gumbClear;
    private javax.swing.JMenuItem gumbOpen;
    private javax.swing.JMenuItem gumbQuit;
    private javax.swing.JMenuItem gumbSpremi;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup osiguranje;
    private javax.swing.JTextField reg_oznaka;
    private javax.swing.JTextPane textContent;
    // End of variables declaration//GEN-END:variables
}
